-- ============================================================
-- 00039_seed_principios_atcL.sql
-- 349 principios activos del grupo ATC L (antineoplásicos,
-- terapia endocrina, inmunoestimulantes, inmunosupresores)
-- obtenidos de la API CIMA (AEMPS), abril 2026.
-- Solo dci + atc_code. Resto de campos pendiente de poblar.
-- ============================================================

INSERT INTO principio_activo (id, dci, atc_code, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'BCG cultivo vivo desecado preparado irrigación vesical', 'L03AX03', now(), now()),
  (gen_random_uuid(), 'Echinacea angustifolia', 'L03A', now(), now()),
  (gen_random_uuid(), 'Fedratinib', 'L01EJ02', now(), now()),
  (gen_random_uuid(), 'L-asparaginasa', 'L01XX02', now(), now()),
  (gen_random_uuid(), 'abatacept', 'L04AA24', now(), now()),
  (gen_random_uuid(), 'abemaciclib', 'L01EF03', now(), now()),
  (gen_random_uuid(), 'abiraterona', 'L02BX03', now(), now()),
  (gen_random_uuid(), 'acalabrutinib', 'L01EL02', now(), now()),
  (gen_random_uuid(), 'adalimumab', 'L04AB04', now(), now()),
  (gen_random_uuid(), 'afatinib', 'L01EB03', now(), now()),
  (gen_random_uuid(), 'aldesleukina', 'L03AC01', now(), now()),
  (gen_random_uuid(), 'alectinib', 'L01ED03', now(), now()),
  (gen_random_uuid(), 'alemtuzumab', 'L04AG06', now(), now()),
  (gen_random_uuid(), 'alpelisib', 'L01EM03', now(), now()),
  (gen_random_uuid(), 'aminolevulinato de metilo', 'L01XD03', now(), now()),
  (gen_random_uuid(), 'amivantamab', 'L01FX18', now(), now()),
  (gen_random_uuid(), 'amsacrina', 'L01XX01', now(), now()),
  (gen_random_uuid(), 'anagrelida', 'L01XX35', now(), now()),
  (gen_random_uuid(), 'anakinra', 'L04AC03', now(), now()),
  (gen_random_uuid(), 'anastrozol', 'L02BG03', now(), now()),
  (gen_random_uuid(), 'anifrolumab', 'L04AG11', now(), now()),
  (gen_random_uuid(), 'apalutamida', 'L02BB05', now(), now()),
  (gen_random_uuid(), 'apremilast', 'L04AA32', now(), now()),
  (gen_random_uuid(), 'arsénico trióxido', 'L01XX27', now(), now()),
  (gen_random_uuid(), 'asciminib', 'L01EA06', now(), now()),
  (gen_random_uuid(), 'atezolizumab', 'L01FF05', now(), now()),
  (gen_random_uuid(), 'avacopán', 'L04AJ05', now(), now()),
  (gen_random_uuid(), 'avapritinib', 'L01EX18', now(), now()),
  (gen_random_uuid(), 'avelumab', 'L01FF04', now(), now()),
  (gen_random_uuid(), 'axicabtagen ciloleucel', 'L01XL03', now(), now()),
  (gen_random_uuid(), 'axitinib', 'L01EK01', now(), now()),
  (gen_random_uuid(), 'azacitidina', 'L01BC07', now(), now()),
  (gen_random_uuid(), 'azatioprina', 'L04AX01', now(), now()),
  (gen_random_uuid(), 'baricitinib', 'L04AF02', now(), now()),
  (gen_random_uuid(), 'basilixmab', 'L04AC02', now(), now()),
  (gen_random_uuid(), 'belantamab mafodotina', 'L01FX15', now(), now()),
  (gen_random_uuid(), 'belatacept', 'L04AA28', now(), now()),
  (gen_random_uuid(), 'belimumab', 'L04AG04', now(), now()),
  (gen_random_uuid(), 'belumosudil', 'L04AA48', now(), now()),
  (gen_random_uuid(), 'belzutifán', 'L01XX74', now(), now()),
  (gen_random_uuid(), 'bendamustina', 'L01AA09', now(), now()),
  (gen_random_uuid(), 'bevacizumab', 'L01FG01', now(), now()),
  (gen_random_uuid(), 'bexaroteno', 'L01XF03', now(), now()),
  (gen_random_uuid(), 'bicalutamida', 'L02BB03', now(), now()),
  (gen_random_uuid(), 'bimekizumab', 'L04AC21', now(), now()),
  (gen_random_uuid(), 'binimetinib', 'L01EE03', now(), now()),
  (gen_random_uuid(), 'bleomicina', 'L01DC01', now(), now()),
  (gen_random_uuid(), 'blinatumomab', 'L01FX07', now(), now()),
  (gen_random_uuid(), 'bortezomib', 'L01XG01', now(), now()),
  (gen_random_uuid(), 'bosutinib', 'L01EA04', now(), now()),
  (gen_random_uuid(), 'brentuximab vedotina', 'L01FX05', now(), now()),
  (gen_random_uuid(), 'brexucabtagén autoleucel', 'L01XL06', now(), now()),
  (gen_random_uuid(), 'brigatinib', 'L01ED04', now(), now()),
  (gen_random_uuid(), 'brodalumab', 'L04AC12', now(), now()),
  (gen_random_uuid(), 'buserelina', 'L02AE01', now(), now()),
  (gen_random_uuid(), 'busulfano', 'L01AB01', now(), now()),
  (gen_random_uuid(), 'cabazitaxel', 'L01CD04', now(), now()),
  (gen_random_uuid(), 'cabozantinib', 'L01EX07', now(), now()),
  (gen_random_uuid(), 'canakinumab', 'L04AC08', now(), now()),
  (gen_random_uuid(), 'capecitabina', 'L01BC06', now(), now()),
  (gen_random_uuid(), 'capivasertib', 'L01EX27', now(), now()),
  (gen_random_uuid(), 'capmatinib', 'L01EP01', now(), now()),
  (gen_random_uuid(), 'carboplatino', 'L01XA02', now(), now()),
  (gen_random_uuid(), 'carfilzomib', 'L01XG02', now(), now()),
  (gen_random_uuid(), 'carmustina', 'L01AD01', now(), now()),
  (gen_random_uuid(), 'catumaxomab', 'L01FX03', now(), now()),
  (gen_random_uuid(), 'cemiplimab', 'L01FF06', now(), now()),
  (gen_random_uuid(), 'ceritinib', 'L01ED02', now(), now()),
  (gen_random_uuid(), 'certolizumab pegol', 'L04AB05', now(), now()),
  (gen_random_uuid(), 'cetuximab', 'L01FE01', now(), now()),
  (gen_random_uuid(), 'ciltacabtagén autoleucel', 'L01XL05', now(), now()),
  (gen_random_uuid(), 'citarabina', 'L01BC01', now(), now()),
  (gen_random_uuid(), 'cladribina', 'L04AA40', now(), now()),
  (gen_random_uuid(), 'clofarabina', 'L01BB06', now(), now()),
  (gen_random_uuid(), 'clorambucilo', 'L01AA02', now(), now()),
  (gen_random_uuid(), 'clormetina', 'L01AA05', now(), now()),
  (gen_random_uuid(), 'cobimetinib', 'L01EE02', now(), now()),
  (gen_random_uuid(), 'crisantaspasa', 'L01XX02', now(), now()),
  (gen_random_uuid(), 'crizotinib', 'L01ED01', now(), now()),
  (gen_random_uuid(), 'crovalimab', 'L04AJ07', now(), now()),
  (gen_random_uuid(), 'dabrafenib', 'L01EC02', now(), now()),
  (gen_random_uuid(), 'dacarbazina', 'L01AX04', now(), now()),
  (gen_random_uuid(), 'dacomitinib', 'L01EB07', now(), now()),
  (gen_random_uuid(), 'danicopán', 'L04AJ09', now(), now()),
  (gen_random_uuid(), 'daratumumab', 'L01FC01', now(), now()),
  (gen_random_uuid(), 'darolutamida', 'L02BB06', now(), now()),
  (gen_random_uuid(), 'darvadstrocel', 'L04AX08', now(), now()),
  (gen_random_uuid(), 'dasatinib', 'L01EA02', now(), now()),
  (gen_random_uuid(), 'daunorubicina', 'L01DB02', now(), now()),
  (gen_random_uuid(), 'daunorubicina + citarabina', 'L01XY01', now(), now()),
  (gen_random_uuid(), 'decitabina', 'L01BC08', now(), now()),
  (gen_random_uuid(), 'decitabina + cedazuridina', 'L01BC58', now(), now()),
  (gen_random_uuid(), 'degarelix', 'L02BX02', now(), now()),
  (gen_random_uuid(), 'deucravacitinib', 'L04AF07', now(), now()),
  (gen_random_uuid(), 'dimetilfumarato', 'L04AX07', now(), now()),
  (gen_random_uuid(), 'dinutuximab beta', 'L01FX06', now(), now()),
  (gen_random_uuid(), 'docetaxel', 'L01CD02', now(), now()),
  (gen_random_uuid(), 'dostarlimab', 'L01FF07', now(), now()),
  (gen_random_uuid(), 'durvalumab', 'L01FF03', now(), now()),
  (gen_random_uuid(), 'eculizumab', 'L04AJ01', now(), now()),
  (gen_random_uuid(), 'efgartigimod alfa', 'L04AL01', now(), now()),
  (gen_random_uuid(), 'elacestrant', 'L02BA04', now(), now()),
  (gen_random_uuid(), 'elotuzumab', 'L01FX08', now(), now()),
  (gen_random_uuid(), 'elranatamab', 'L01FX32', now(), now()),
  (gen_random_uuid(), 'encorafenib', 'L01EC03', now(), now()),
  (gen_random_uuid(), 'enfortumab vedotina', 'L01FX13', now(), now()),
  (gen_random_uuid(), 'entrectinib', 'L01EX14', now(), now()),
  (gen_random_uuid(), 'enzalutamida', 'L02BB04', now(), now()),
  (gen_random_uuid(), 'epcoritamab', 'L01FX27', now(), now()),
  (gen_random_uuid(), 'epirubicina', 'L01DB03', now(), now()),
  (gen_random_uuid(), 'erdafitinib', 'L01EN01', now(), now()),
  (gen_random_uuid(), 'eribulina', 'L01XX41', now(), now()),
  (gen_random_uuid(), 'erlotinib', 'L01EB02', now(), now()),
  (gen_random_uuid(), 'espesolimab', 'L04AC22', now(), now()),
  (gen_random_uuid(), 'estramustina', 'L01XX11', now(), now()),
  (gen_random_uuid(), 'estreptozocina', 'L01AD04', now(), now()),
  (gen_random_uuid(), 'etanercept', 'L04AB01', now(), now()),
  (gen_random_uuid(), 'etoposido', 'L01CB01', now(), now()),
  (gen_random_uuid(), 'etrasimod', 'L04AE05', now(), now()),
  (gen_random_uuid(), 'everolimus', 'L01EG02', now(), now()),
  (gen_random_uuid(), 'exemestano', 'L02BG06', now(), now()),
  (gen_random_uuid(), 'filgotinib', 'L04AF04', now(), now()),
  (gen_random_uuid(), 'filgrastim', 'L03AA02', now(), now()),
  (gen_random_uuid(), 'fingolimod', 'L04AE01', now(), now()),
  (gen_random_uuid(), 'fludarabina', 'L01BB05', now(), now()),
  (gen_random_uuid(), 'fluorouracilo', 'L01BC02', now(), now()),
  (gen_random_uuid(), 'fluorouracilo + ácido salicílico', 'L01BC52', now(), now()),
  (gen_random_uuid(), 'flutamida', 'L02BB01', now(), now()),
  (gen_random_uuid(), 'fotemustina', 'L01AD05', now(), now()),
  (gen_random_uuid(), 'fruquintinib', 'L01EK04', now(), now()),
  (gen_random_uuid(), 'fulvestrant', 'L02BA03', now(), now()),
  (gen_random_uuid(), 'fumarato de diroximel', 'L04AX09', now(), now()),
  (gen_random_uuid(), 'fumarato de tegomil', 'L04AX10', now(), now()),
  (gen_random_uuid(), 'futibatinib', 'L01EN04', now(), now()),
  (gen_random_uuid(), 'gefitinib', 'L01EB01', now(), now()),
  (gen_random_uuid(), 'gemcitabina', 'L01BC05', now(), now()),
  (gen_random_uuid(), 'gemtuzumab ozogamicina', 'L01FX02', now(), now()),
  (gen_random_uuid(), 'gilteritinib', 'L01EX13', now(), now()),
  (gen_random_uuid(), 'glasdegib', 'L01XJ03', now(), now()),
  (gen_random_uuid(), 'glatiramero acetato', 'L03AX13', now(), now()),
  (gen_random_uuid(), 'glofitamab', 'L01FX28', now(), now()),
  (gen_random_uuid(), 'golimumab', 'L04AB06', now(), now()),
  (gen_random_uuid(), 'goserelina', 'L02AE03', now(), now()),
  (gen_random_uuid(), 'guselkumab', 'L04AC16', now(), now()),
  (gen_random_uuid(), 'hidroxicarbamida', 'L01XX05', now(), now()),
  (gen_random_uuid(), 'histamina dihidrocloruro', 'L03AX14', now(), now()),
  (gen_random_uuid(), 'ibrutinib', 'L01EL01', now(), now()),
  (gen_random_uuid(), 'idarubicina', 'L01DB06', now(), now()),
  (gen_random_uuid(), 'idecabtagén vicleucel', 'L01XL07', now(), now()),
  (gen_random_uuid(), 'idelalisib', 'L01EM01', now(), now()),
  (gen_random_uuid(), 'ifosfamida', 'L01AA06', now(), now()),
  (gen_random_uuid(), 'imatinib', 'L01EA01', now(), now()),
  (gen_random_uuid(), 'imlifidasa', 'L04AA41', now(), now()),
  (gen_random_uuid(), 'inavolisib', 'L01X', now(), now()),
  (gen_random_uuid(), 'inebilizumab', 'L04AG10', now(), now()),
  (gen_random_uuid(), 'infliximab', 'L04AB02', now(), now()),
  (gen_random_uuid(), 'inmunoglobulina antitimocítica de conejo', 'L04AA04', now(), now()),
  (gen_random_uuid(), 'inotuzumab ozogamicina', 'L01FB01', now(), now()),
  (gen_random_uuid(), 'interferon alfa-2a', 'L03AB04', now(), now()),
  (gen_random_uuid(), 'interferon alfa-2b', 'L03AB05', now(), now()),
  (gen_random_uuid(), 'interferon beta-1a', 'L03AB07', now(), now()),
  (gen_random_uuid(), 'interferon beta-1b', 'L03AB08', now(), now()),
  (gen_random_uuid(), 'interferon gamma-1b', 'L03AB03', now(), now()),
  (gen_random_uuid(), 'ipilimumab', 'L01FX04', now(), now()),
  (gen_random_uuid(), 'iptacopán', 'L04AJ08', now(), now()),
  (gen_random_uuid(), 'irinotecán', 'L01CE02', now(), now()),
  (gen_random_uuid(), 'isatuximab', 'L01FC02', now(), now()),
  (gen_random_uuid(), 'ivosidenib', 'L01XM02', now(), now()),
  (gen_random_uuid(), 'ixazomib', 'L01XG03', now(), now()),
  (gen_random_uuid(), 'ixekizumab', 'L04AC13', now(), now()),
  (gen_random_uuid(), 'lapatinib', 'L01EH01', now(), now()),
  (gen_random_uuid(), 'larotrectinib', 'L01EX12', now(), now()),
  (gen_random_uuid(), 'lazertinib', 'L01EB09', now(), now()),
  (gen_random_uuid(), 'leflunomida', 'L04AK01', now(), now()),
  (gen_random_uuid(), 'lenalidomida', 'L04AX04', now(), now()),
  (gen_random_uuid(), 'lenograstim', 'L03AA10', now(), now()),
  (gen_random_uuid(), 'lenvatinib', 'L01EX08', now(), now()),
  (gen_random_uuid(), 'letrozol', 'L02BG04', now(), now()),
  (gen_random_uuid(), 'leuprorelina', 'L02AE02', now(), now()),
  (gen_random_uuid(), 'linvoseltamab', 'L01F', now(), now()),
  (gen_random_uuid(), 'lipegfilgrastim', 'L03AA14', now(), now()),
  (gen_random_uuid(), 'lisocabtagén maraleucel', 'L01XL08', now(), now()),
  (gen_random_uuid(), 'lomustina', 'L01AD02', now(), now()),
  (gen_random_uuid(), 'loncastuximab tesirina', 'L01FX22', now(), now()),
  (gen_random_uuid(), 'lorlatinib', 'L01ED05', now(), now()),
  (gen_random_uuid(), 'medroxiprogesterona', 'L02AB02', now(), now()),
  (gen_random_uuid(), 'megestrol', 'L02AB01', now(), now()),
  (gen_random_uuid(), 'melfalán', 'L01AA03', now(), now()),
  (gen_random_uuid(), 'melfalán flufenamida', 'L01AA10', now(), now()),
  (gen_random_uuid(), 'mercaptopurina', 'L01BB02', now(), now()),
  (gen_random_uuid(), 'metotrexato', 'L04AX03', now(), now()),
  (gen_random_uuid(), 'metoxaleno', 'L03A', now(), now()),
  (gen_random_uuid(), 'micofenolato mofetilo', 'L04AA06', now(), now()),
  (gen_random_uuid(), 'midostaurina', 'L01EX10', now(), now()),
  (gen_random_uuid(), 'mifamurtida', 'L03AX15', now(), now()),
  (gen_random_uuid(), 'mirdametinib', 'L01EE05', now(), now()),
  (gen_random_uuid(), 'mirikizumab', 'L04AC24', now(), now()),
  (gen_random_uuid(), 'mirvetuximab soravtansina', 'L01FX26', now(), now()),
  (gen_random_uuid(), 'mitomicina', 'L01DC03', now(), now()),
  (gen_random_uuid(), 'mitotano', 'L01XX23', now(), now()),
  (gen_random_uuid(), 'mitoxantrona', 'L01DB07', now(), now()),
  (gen_random_uuid(), 'mogamulizumab', 'L01FX09', now(), now()),
  (gen_random_uuid(), 'momelotinib', 'L01EJ04', now(), now()),
  (gen_random_uuid(), 'mosunetuzumab', 'L01FX25', now(), now()),
  (gen_random_uuid(), 'natalizumab', 'L04AG03', now(), now()),
  (gen_random_uuid(), 'necitumumab', 'L01FE03', now(), now()),
  (gen_random_uuid(), 'nelarabina', 'L01BB07', now(), now()),
  (gen_random_uuid(), 'neratinib', 'L01EH02', now(), now()),
  (gen_random_uuid(), 'nilotinib', 'L01EA03', now(), now()),
  (gen_random_uuid(), 'nintedanib', 'L01EX09', now(), now()),
  (gen_random_uuid(), 'nipocalimab', 'L04AL03', now(), now()),
  (gen_random_uuid(), 'niraparib', 'L01XK02', now(), now()),
  (gen_random_uuid(), 'niraparib + abiraterona', 'L01XK52', now(), now()),
  (gen_random_uuid(), 'nirogacestat', 'L01XX81', now(), now()),
  (gen_random_uuid(), 'nivolumab', 'L01FF01', now(), now()),
  (gen_random_uuid(), 'nivolumab + relatlimab', 'L01FY02', now(), now()),
  (gen_random_uuid(), 'obinutuzumab', 'L01FA03', now(), now()),
  (gen_random_uuid(), 'ocrelizumab', 'L04AG08', now(), now()),
  (gen_random_uuid(), 'odronextamab', 'L01FX34', now(), now()),
  (gen_random_uuid(), 'ofatumumab', 'L04AG12', now(), now()),
  (gen_random_uuid(), 'olaparib', 'L01XK01', now(), now()),
  (gen_random_uuid(), 'osimertinib', 'L01EB04', now(), now()),
  (gen_random_uuid(), 'oxaliplatino', 'L01XA03', now(), now()),
  (gen_random_uuid(), 'ozanimod', 'L04AE02', now(), now()),
  (gen_random_uuid(), 'paclitaxel', 'L01CD01', now(), now()),
  (gen_random_uuid(), 'padeliporfina', 'L01XD07', now(), now()),
  (gen_random_uuid(), 'palbociclib', 'L01EF01', now(), now()),
  (gen_random_uuid(), 'panitumumab', 'L01FE02', now(), now()),
  (gen_random_uuid(), 'panobinostat', 'L01XH03', now(), now()),
  (gen_random_uuid(), 'pazopanib', 'L01EX03', now(), now()),
  (gen_random_uuid(), 'pegaspargasa', 'L01XX24', now(), now()),
  (gen_random_uuid(), 'pegcetacoplán', 'L04AJ03', now(), now()),
  (gen_random_uuid(), 'pegfilgrastim', 'L03AA13', now(), now()),
  (gen_random_uuid(), 'peginterferón alfa-2a', 'L03AB11', now(), now()),
  (gen_random_uuid(), 'peginterferón alfa-2b', 'L03AB10', now(), now()),
  (gen_random_uuid(), 'peginterferón beta-1a', 'L03AB13', now(), now()),
  (gen_random_uuid(), 'pembrolizumab', 'L01FF02', now(), now()),
  (gen_random_uuid(), 'pemetrexed', 'L01BA04', now(), now()),
  (gen_random_uuid(), 'pemigatinib', 'L01EN02', now(), now()),
  (gen_random_uuid(), 'pentostatina', 'L01XX08', now(), now()),
  (gen_random_uuid(), 'pertuzumab', 'L01FD02', now(), now()),
  (gen_random_uuid(), 'pertuzumab + trastuzumab', 'L01FY01', now(), now()),
  (gen_random_uuid(), 'pirfenidona', 'L04AX05', now(), now()),
  (gen_random_uuid(), 'pirtobrutinib', 'L01EL05', now(), now()),
  (gen_random_uuid(), 'pixantrona', 'L01DB11', now(), now()),
  (gen_random_uuid(), 'plerixafor', 'L03AX16', now(), now()),
  (gen_random_uuid(), 'polatuzumab vedotina', 'L01FX14', now(), now()),
  (gen_random_uuid(), 'pomalidomida', 'L04AX06', now(), now()),
  (gen_random_uuid(), 'ponatinib', 'L01EA05', now(), now()),
  (gen_random_uuid(), 'ponesimod', 'L04AE04', now(), now()),
  (gen_random_uuid(), 'pralsetinib', 'L01EX23', now(), now()),
  (gen_random_uuid(), 'procarbazina', 'L01XB01', now(), now()),
  (gen_random_uuid(), 'quizartinib', 'L01EX11', now(), now()),
  (gen_random_uuid(), 'raltitrexed', 'L01BA03', now(), now()),
  (gen_random_uuid(), 'ramucirumab', 'L01FG02', now(), now()),
  (gen_random_uuid(), 'ravulizumab', 'L04AJ02', now(), now()),
  (gen_random_uuid(), 'regorafenib', 'L01EX05', now(), now()),
  (gen_random_uuid(), 'relugolix', 'L02BX04', now(), now()),
  (gen_random_uuid(), 'retifanlimab', 'L01FF10', now(), now()),
  (gen_random_uuid(), 'ribociclib', 'L01EF02', now(), now()),
  (gen_random_uuid(), 'ripretinib', 'L01EX19', now(), now()),
  (gen_random_uuid(), 'risankizumab', 'L04AC18', now(), now()),
  (gen_random_uuid(), 'ritlecitinib', 'L04AF08', now(), now()),
  (gen_random_uuid(), 'rituximab', 'L01FA01', now(), now()),
  (gen_random_uuid(), 'ropeginterferón alfa-2b', 'L03AB15', now(), now()),
  (gen_random_uuid(), 'rozanolixizumab', 'L04AL02', now(), now()),
  (gen_random_uuid(), 'rucaparib', 'L01XK03', now(), now()),
  (gen_random_uuid(), 'ruxolitinib', 'L01EJ01', now(), now()),
  (gen_random_uuid(), 'sacituzumab govitecán', 'L01FX17', now(), now()),
  (gen_random_uuid(), 'sarilumab', 'L04AC14', now(), now()),
  (gen_random_uuid(), 'satralizumab', 'L04AC19', now(), now()),
  (gen_random_uuid(), 'secukinumab', 'L04AC10', now(), now()),
  (gen_random_uuid(), 'selinexor', 'L01XX66', now(), now()),
  (gen_random_uuid(), 'selpercatinib', 'L01EX22', now(), now()),
  (gen_random_uuid(), 'selumetinib', 'L01EE04', now(), now()),
  (gen_random_uuid(), 'serplulimab', 'L01FF12', now(), now()),
  (gen_random_uuid(), 'siltuximab', 'L04AC11', now(), now()),
  (gen_random_uuid(), 'siponimod', 'L04AE03', now(), now()),
  (gen_random_uuid(), 'sirolimus', 'L04AH01', now(), now()),
  (gen_random_uuid(), 'sonidegib', 'L01XJ02', now(), now()),
  (gen_random_uuid(), 'sorafenib', 'L01EX02', now(), now()),
  (gen_random_uuid(), 'sotorasib', 'L01XX73', now(), now()),
  (gen_random_uuid(), 'sugemalimab', 'L01FF11', now(), now()),
  (gen_random_uuid(), 'sunitinib', 'L01EX01', now(), now()),
  (gen_random_uuid(), 'sutimlimab', 'L04AJ04', now(), now()),
  (gen_random_uuid(), 'tabelecleucel', 'L01XL09', now(), now()),
  (gen_random_uuid(), 'tacrolimus', 'L04AD02', now(), now()),
  (gen_random_uuid(), 'tafasitamab', 'L01FX12', now(), now()),
  (gen_random_uuid(), 'tagraxofusp', 'L01XX67', now(), now()),
  (gen_random_uuid(), 'talazoparib', 'L01XK04', now(), now()),
  (gen_random_uuid(), 'talidomida', 'L04AX02', now(), now()),
  (gen_random_uuid(), 'talimogén laherparepvec', 'L01XL02', now(), now()),
  (gen_random_uuid(), 'talquetamab', 'L01FX29', now(), now()),
  (gen_random_uuid(), 'tamoxifeno', 'L02BA01', now(), now()),
  (gen_random_uuid(), 'tasonermina', 'L03AX11', now(), now()),
  (gen_random_uuid(), 'tebentafusp', 'L01XX75', now(), now()),
  (gen_random_uuid(), 'teclistamab', 'L01FX24', now(), now()),
  (gen_random_uuid(), 'tegafur', 'L01BC03', now(), now()),
  (gen_random_uuid(), 'tegafur + gimeracilo + oteracilo', 'L01BC53', now(), now()),
  (gen_random_uuid(), 'temoporfina', 'L01XD05', now(), now()),
  (gen_random_uuid(), 'temozolomida', 'L01AX03', now(), now()),
  (gen_random_uuid(), 'temsirolimus', 'L01EG01', now(), now()),
  (gen_random_uuid(), 'tepotinib', 'L01EP02', now(), now()),
  (gen_random_uuid(), 'teprotumumab', 'L04AG13', now(), now()),
  (gen_random_uuid(), 'teriflunomida', 'L04AK02', now(), now()),
  (gen_random_uuid(), 'tildrakizumab', 'L04AC17', now(), now()),
  (gen_random_uuid(), 'tioguanina', 'L01BB03', now(), now()),
  (gen_random_uuid(), 'tiotepa', 'L01AC01', now(), now()),
  (gen_random_uuid(), 'tisagenlecleucel', 'L01XL04', now(), now()),
  (gen_random_uuid(), 'tislelizumab', 'L01FF09', now(), now()),
  (gen_random_uuid(), 'tisotumab vedotina', 'L01FX23', now(), now()),
  (gen_random_uuid(), 'tivozanib', 'L01EK03', now(), now()),
  (gen_random_uuid(), 'tocilizumab', 'L04AC07', now(), now()),
  (gen_random_uuid(), 'tofacitinib', 'L04AF01', now(), now()),
  (gen_random_uuid(), 'topotecán', 'L01CE01', now(), now()),
  (gen_random_uuid(), 'toremifeno', 'L02BA02', now(), now()),
  (gen_random_uuid(), 'toripalimab', 'L01FF13', now(), now()),
  (gen_random_uuid(), 'trabectedina', 'L01CX01', now(), now()),
  (gen_random_uuid(), 'trametinib', 'L01EE01', now(), now()),
  (gen_random_uuid(), 'trastuzumab', 'L01FD01', now(), now()),
  (gen_random_uuid(), 'trastuzumab deruxtecán', 'L01FD04', now(), now()),
  (gen_random_uuid(), 'trastuzumab emtansina', 'L01FD03', now(), now()),
  (gen_random_uuid(), 'tremelimumab', 'L01FX20', now(), now()),
  (gen_random_uuid(), 'treosulfano', 'L01AB02', now(), now()),
  (gen_random_uuid(), 'tretinoína', 'L01XF01', now(), now()),
  (gen_random_uuid(), 'trifluridina + tipiracilo', 'L01BC59', now(), now()),
  (gen_random_uuid(), 'triptorelina', 'L02AE04', now(), now()),
  (gen_random_uuid(), 'tucatinib', 'L01EH03', now(), now()),
  (gen_random_uuid(), 'ublituximab', 'L04AG14', now(), now()),
  (gen_random_uuid(), 'upadacitinib', 'L04AF03', now(), now()),
  (gen_random_uuid(), 'ustekinumab', 'L04AC05', now(), now()),
  (gen_random_uuid(), 'vandetanib', 'L01EX04', now(), now()),
  (gen_random_uuid(), 'vedolizumab', 'L04AG05', now(), now()),
  (gen_random_uuid(), 'vemurafenib', 'L01EC01', now(), now()),
  (gen_random_uuid(), 'venetoclax', 'L01XX52', now(), now()),
  (gen_random_uuid(), 'vimseltinib', 'L01EX29', now(), now()),
  (gen_random_uuid(), 'vinblastina', 'L01CA01', now(), now()),
  (gen_random_uuid(), 'vincristina', 'L01CA02', now(), now()),
  (gen_random_uuid(), 'vindesina', 'L01CA03', now(), now()),
  (gen_random_uuid(), 'vinflunina', 'L01CA05', now(), now()),
  (gen_random_uuid(), 'vinorelbina', 'L01CA04', now(), now()),
  (gen_random_uuid(), 'vismodegib', 'L01XJ01', now(), now()),
  (gen_random_uuid(), 'voclosporina', 'L04AD03', now(), now()),
  (gen_random_uuid(), 'vorasidenib', 'L01XM04', now(), now()),
  (gen_random_uuid(), 'zanubrutinib', 'L01EL03', now(), now()),
  (gen_random_uuid(), 'zilucoplán', 'L04AJ06', now(), now()),
  (gen_random_uuid(), 'zolbetuximab', 'L01FX31', now(), now()),
  (gen_random_uuid(), 'ácido 5-aminolevulínico', 'L01XD04', now(), now()),
  (gen_random_uuid(), 'ácido micofenólico', 'L04AA06', now(), now())
ON CONFLICT (dci) DO NOTHING;